// All CV content lives here. Edit this file to update the site.
// Shared values go in CV.common, translated text in CV.en / CV.fr.
const CV = {
  common: {
    name: "Pierre Adam",
    handle: "pierreadam",
    location: "Strasbourg, France",
    pdf: null, // set to "cv.pdf" once the file is in the folder
    links: [
      { label: "github", url: "https://github.com/PierreAdam" },
      { label: "linkedin", url: "https://www.linkedin.com/in/pierreadam57" },
    ],
    projects: [
      { name: "sound-barrier", tags: ["Python", "FastAPI", "TypeScript", "PostgreSQL"], url: "https://github.com/PierreAdam/sound-barrier" },
      { name: "java-datatables", tags: ["Java", "jOOQ", "Maven"], url: "https://github.com/PierreAdam/java-datatables" },
      { name: "play-jooq", tags: ["Scala", "Play Framework", "jOOQ"], url: "https://github.com/PierreAdam/play-jooq" },
    ],
  },

  en: {
    title: "Pierre Adam | CTO, payment systems",
    roles: ["CTO", "Payment systems engineer", "Java developer"],
    pitch: "I build payment and ordering systems that keep working when the network doesn't.",
    about: [
      "I'm the CTO of Merim Digital Payment, the payment branch of Merim Groupe, based in Strasbourg. I've been building payment systems for over ten years, first for events at MyBee Events, then at PayinTech, which Merim acquired in 2021.",
      "These days my work sits somewhere between the restaurant counter and the bank: card payments on kiosks and POS, order intake, delivery integrations and NF525 fiscal compliance. I manage teams, but I still write code, mostly Java.",
      "Outside work I tinker with Python, Arduino boards and OpenSCAD. I work in both French and English.",
    ],
    experience: [
      {
        period: "2021 - now", title: "CTO", company: "Merim Groupe",
        text: "Joined when Merim acquired PayinTech. I run the technical side of everything payment-related in the group, plus part of the group's R&D.",
        points: [
          "Stabilized the backend that handles payments and in-store ordering",
          "Adapted the Merim kiosk software so it runs with Zelty",
          "Integrated card payments on self-service kiosks (ERT45) and POS (ERT10)",
          "Built a platform that brings delivery orders into the restaurant",
          "Wrote an NF525 fiscal core that runs on every device allowed to close an order, so a restaurant keeps selling even if the network or the local server goes down",
          "Kitchen orchestrator for quick-service restaurants: it reads incoming orders, decides what to cook first and sends each one to production based on business rules",
          "Linux modernisation: packaged recent software for the Linux systems already running in restaurants, which couldn't install it on their own. Restaurants get modern tech without us upgrading the whole fleet, which would have cost a fortune",
        ],
      },
      {
        period: "2017 - 2021", title: "CTO", company: "PayinTech",
        text: "Ran the tech and QA teams, scoped and estimated new projects, looked after every server and platform we had, and kept writing Java on a distributed system.",
      },
      {
        period: "2014 - 2017", title: "Head of R&D", company: "PayinTech",
        text: "Designed and built the PayinTech payment solution from scratch with a team of four. Also did feasibility studies for new products and added modules to MyBee Events.",
      },
      {
        period: "2020", title: "Freelance software engineer", company: "self-employed",
        text: "Seven months of freelance development work.",
      },
      {
        period: "2015 - 2017", title: "IT teacher", company: "self-employed",
        text: "Worked with higher-education schools on demand: technical advice, reviewing technical documents, assessing student projects and sitting on thesis juries.",
      },
      {
        period: "2013 - 2014", title: "R&D developer, then lead developer", company: "MyBee Events",
        text: "Rebuilt the cashless payment system used at events, fixed bugs and shipped features in STM32 firmware running FreeRTOS, and built the stats platform and event configuration UI. Also supported our resellers.",
      },
      {
        period: "2012", title: ".NET developer", company: "Bull",
        text: "Built internal project management tools and worked on the maintenance contract for the French customs.",
      },
      {
        period: "2011 - 2012", title: "Teaching assistant", company: "Epitech",
        text: "Gave classes, graded student projects, helped students who were struggling and kept the school's systems running.",
      },
    ],
    skills: {
      leadership: ["Team management", "Project management", "Estimation", "QA"],
      payments: ["Card payments", "Kiosk & POS", "NF525", "Order intake"],
      backend: ["Java", "Scala", "Play Framework", "Python", "FastAPI", ".NET", "Maven", "sbt"],
      data: ["PostgreSQL", "SQLAlchemy", "jOOQ", "Ebean"],
      frontend: ["HTML", "CSS", "JavaScript", "TypeScript"],
      "embedded & ops": ["C / C++", "STM32", "FreeRTOS", "Arduino", "MQTT", "Linux", "Docker", "CI/CD"],
    },
    projectText: {
      "sound-barrier": "Self-hosted music server that speaks the Subsonic API, with its own web player, MusicBrainz tagging on import, audiobooks and podcasts, and casting to TVs. I use it every day.",
      "java-datatables": "Server-side DataTables for any Java project, not just Play. It's the successor of my play-datatables library, with a framework-agnostic core and a jOOQ data provider.",
      "play-jooq": "Brings jOOQ into Play Framework as a proper module, so it's configured and injected like the rest of the app instead of being wired by hand.",
    },
    education: [
      { period: "2009 - 2014", title: "Expert in Information Technology", school: "Epitech, European Institute of Technology" },
      { period: "2012 - 2013", title: "Telecommunications engineering (exchange year)", school: "Saint Petersburg University of Telecommunications" },
    ],
  },

  fr: {
    title: "Pierre Adam | Directeur technique, systèmes de paiement",
    roles: ["Directeur technique", "Ingénieur paiement", "Développeur Java"],
    pitch: "Je conçois des systèmes de paiement et de prise de commande fiables, capables de fonctionner même en cas de perte du réseau.",
    about: [
      "Directeur technique de Merim Digital Payment, la branche paiement de Merim Groupe, je suis basé à Strasbourg. Je travaille depuis plus de dix ans sur des systèmes de paiement, d'abord dans l'événementiel chez MyBee Events, puis chez PayinTech, société rachetée par Merim Groupe en 2021.",
      "Mon périmètre couvre aujourd'hui l'ensemble de la chaîne, du restaurant jusqu'à la banque : paiement par carte sur bornes et caisses, prise de commande, intégration des plateformes de livraison et conformité fiscale NF525. En parallèle du management des équipes, je reste impliqué dans le développement, principalement en Java.",
      "Sur mon temps personnel, je développe des projets en Python, sur Arduino et avec OpenSCAD. Je travaille indifféremment en français et en anglais.",
    ],
    experience: [
      {
        period: "2021 - aujourd'hui", title: "Directeur technique", company: "Merim Groupe",
        text: "J'ai rejoint Merim Groupe en mars 2021 à la suite de l'acquisition de PayinTech. J'y assure la direction technique des projets liés au paiement ainsi qu'une partie de la R&D du groupe.",
        points: [
          "Stabilisation des composants backend responsables du paiement et de la prise de commande en restaurant",
          "Adaptation du logiciel des bornes Merim pour leur utilisation avec Zelty",
          "Intégration du paiement bancaire sur borne autonome (contrat ERT45) et sur caisse (contrat ERT10)",
          "Réalisation d'une plateforme d'intégration des commandes en livraison",
          "Création d'un cœur fiscal NF525 embarqué sur chaque équipement habilité à fiscaliser une commande (caisse, borne, etc.), garantissant la continuité de service en cas de perte du réseau ou du serveur du restaurant",
          "Orchestrateur de cuisine pour la restauration rapide : analyse et priorisation des commandes entrantes, puis lancement en production selon des règles métier",
          "Modernisation Linux : intégration de paquets récents sur des systèmes Linux déjà déployés en restaurant qui ne les prenaient pas en charge nativement, permettant l'accès à des technologies actuelles sans mise à niveau complète du parc, dont le coût aurait été très élevé",
        ],
      },
      {
        period: "2017 - 2021", title: "Directeur technique", company: "PayinTech",
        text: "Management des équipes technique et QA, évaluation et chiffrage des nouveaux projets, administration de l'ensemble des serveurs et plateformes, et développement Java sur un environnement distribué.",
      },
      {
        period: "2014 - 2017", title: "Directeur R&D", company: "PayinTech",
        text: "Conception et réalisation de la solution de paiement PayinTech à la tête d'une équipe de quatre personnes. Études de faisabilité des nouveaux produits et développement de nouveaux modules pour la solution MyBee Events.",
      },
      {
        period: "2020", title: "Ingénieur logiciel freelance", company: "indépendant",
        text: "Missions de développement logiciel en freelance pendant sept mois.",
      },
      {
        period: "2015 - 2017", title: "Enseignant en informatique", company: "indépendant",
        text: "Interventions auprès d'écoles de l'enseignement supérieur : conseil technique, relecture de documents techniques, évaluation des charges de travail et des projets, participation aux jurys de soutenance.",
      },
      {
        period: "2013 - 2014", title: "Développeur R&D, puis lead developer", company: "MyBee Events",
        text: "Refonte du système de paiement cashless pour l'événementiel, maintenance et évolution d'un firmware STM32 sous FreeRTOS, développement de la plateforme de statistiques et de l'interface de configuration des événements. Support auprès des revendeurs.",
      },
      {
        period: "2012", title: "Développeur .NET", company: "Bull",
        text: "Développement d'outils internes de gestion de projet et participation à la TMA des douanes françaises.",
      },
      {
        period: "2011 - 2012", title: "Assistant pédagogique", company: "Epitech",
        text: "Animation de cours, correction des projets étudiants, accompagnement des étudiants en difficulté et maintenance du système informatique de l'école.",
      },
    ],
    skills: {
      management: ["Gestion d'équipe", "Gestion de projet", "Chiffrage", "QA"],
      paiement: ["Paiement carte", "Bornes & caisses", "NF525", "Prise de commande"],
      backend: ["Java", "Scala", "Play Framework", "Python", "FastAPI", ".NET", "Maven", "sbt"],
      "données": ["PostgreSQL", "SQLAlchemy", "jOOQ", "Ebean"],
      frontend: ["HTML", "CSS", "JavaScript", "TypeScript"],
      "embarqué & ops": ["C / C++", "STM32", "FreeRTOS", "Arduino", "MQTT", "Linux", "Docker", "CI/CD"],
    },
    projectText: {
      "sound-barrier": "Serveur musical auto-hébergé compatible avec l'API Subsonic : lecteur web intégré, identification MusicBrainz à l'import, gestion des livres audio et podcasts, diffusion sur TV. Utilisé au quotidien.",
      "java-datatables": "Gestion côté serveur de DataTables pour tout projet Java, au-delà de Play. Successeur de ma bibliothèque play-datatables, avec un cœur indépendant du framework et un fournisseur de données jOOQ.",
      "play-jooq": "Intègre jOOQ comme un véritable module Play Framework : configuration et injection de dépendances identiques au reste de l'application, sans câblage manuel.",
    },
    education: [
      { period: "2009 - 2014", title: "Expert en technologies de l'information", school: "Epitech, European Institute of Technology" },
      { period: "2012 - 2013", title: "Ingénierie des télécommunications (année d'échange)", school: "Université des télécommunications de Saint-Pétersbourg" },
    ],
  },
};

// Interface text (menus, headings, intro, console)
const UI = {
  en: {
    nav: { about: "about", experience: "experience", skills: "skills", projects: "projects", contact: "contact" },
    sections: { about: "about", experience: "experience", skills: "skills", projects: "side projects", education: "education", contact: "contact" },
    viewProjects: "see my projects",
    download: "download cv.pdf",
    hint: "psst, press <kbd>~</kbd> to open a terminal",
    contactText: "Want to talk payments, a project or a job? Reach out on LinkedIn.",
    footer: "written in HTML, CSS and plain JS",
    skip: "skip ›",
    boot: (c) => [
      [false, "Loading Linux 6.12.0-cv ..."],
      [false, "Loading initial ramdisk ..."],
      [false, ""],
      [false, "Welcome to CV Linux!"],
      [false, ""],
      [true, "Started Journal Service."],
      [true, "Mounted /home/guest."],
      [true, "Reached target Local File Systems."],
      [true, "Started Network Manager."],
      [true, `Loaded experience.txt (${c.experience} entries).`],
      [true, `Loaded skills.txt (${c.skills} packages).`],
      [true, `Loaded projects.txt (${c.projects} projects).`],
      [true, "Started NF525 Fiscal Core."],
      [true, "Started Card Payment Service."],
      [true, "Reached target Multi-User System."],
    ],
    startx: ["xinit: starting graphical session...", "loading pierreadam.js ▸"],
    welcome: "welcome! type 'help' to see what I understand.",
    helpTitle: "available commands:",
    cmds: {
      help: "show this list",
      whoami: "who I am",
      ls: "list the files",
      cat: "read a file (e.g. cat about.txt)",
      neofetch: "system information, the fancy way",
      pay: "try the card terminal (pay 12.50, pay --offline)",
      matrix: "follow the white rabbit",
      hack: "hack the mainframe",
      pwd: "where am I",
      date: "today's date",
      uname: "system name (try uname -a)",
      echo: "repeat what you type",
      history: "commands typed so far",
      man: "manual of a command (e.g. man pay)",
      lang: "change the language",
      restart: "see the site again like the first time",
      clear: "clear the screen",
      exit: "close the terminal",
    },
    notFound: (c) => `command not found: ${c}. try 'help'`,
    langSet: "language set to english",
    langUsage: (cur, list) => `usage: lang <${list.join("|")}>\ncurrent language: ${cur}`,
    langUnknown: (l) => `lang: unknown language '${l}'`,
    catMissing: "cat: missing file operand. try 'ls'",
    catNoFile: (f) => `cat: ${f}: no such file or directory`,
    manUsage: "what manual page do you want? e.g. man cat",
    manNone: (c) => `no manual entry for ${c}`,
    uptime: (y) => `${y} years in software`,
    rm: "rm: nice try. this CV is read-only, and so is my production database.",
    vim: "you're now stuck in vim forever. just kidding, there's no editor here. you're safe.",
    cd: "cd: there's only ~ here. it's a small place.",
    matrixEnd: "wake up, guest... the CV has you.",
    restart: ["Broadcast message from guest@pierreadam:", "The system is going down for reboot NOW!", "[  OK  ] Stopped pierreadam.js", "rebooting..."],
    hack: {
      steps: ["bypassing firewall", "decrypting mainframe", "downloading cv.txt"],
      granted: "ACCESS GRANTED",
      end: "...it was public anyway. try 'cat about.txt'",
    },
    pay: {
      amount: "amount:",
      insert: "insert or tap your card",
      reading: "reading card",
      pin: "PIN:",
      auth: "authorizing with the bank",
      offline: "network lost!",
      offlineOk: "no problem: the NF525 core signs the ticket locally and the restaurant keeps selling.",
      offlineTag: "OFFLINE, SYNC PENDING",
      synced: "ticket queued, it will be sent as soon as the network is back.",
      approved: "APPROVED",
      shop: "PIERRE'S DINER",
      item: "coffee",
      thanks: "thank you, see you soon",
      invalid: "pay: invalid amount. usage: pay [amount] [--offline]",
    },
    sudo: "nice try. this incident will be reported.",
  },
  fr: {
    nav: { about: "profil", experience: "parcours", skills: "compétences", projects: "projets", contact: "contact" },
    sections: { about: "profil", experience: "parcours", skills: "compétences", projects: "projets perso", education: "formation", contact: "contact" },
    viewProjects: "voir mes projets",
    download: "télécharger cv.pdf",
    hint: "astuce : appuyez sur <kbd>~</kbd> pour ouvrir un terminal",
    contactText: "Pour échanger sur un projet ou une opportunité, n'hésitez pas à me contacter via LinkedIn.",
    footer: "écrit en HTML, CSS et JavaScript, sans framework",
    skip: "passer ›",
    boot: (c) => [
      [false, "Chargement de Linux 6.12.0-cv ..."],
      [false, "Chargement du disque mémoire initial ..."],
      [false, ""],
      [false, "Bienvenue sur CV Linux !"],
      [false, ""],
      [true, "Service de journalisation démarré."],
      [true, "/home/guest monté."],
      [true, "Cible Systèmes de fichiers locaux atteinte."],
      [true, "Network Manager démarré."],
      [true, `experience.txt chargé (${c.experience} entrées).`],
      [true, `skills.txt chargé (${c.skills} paquets).`],
      [true, `projects.txt chargé (${c.projects} projets).`],
      [true, "Cœur fiscal NF525 démarré."],
      [true, "Service de paiement carte démarré."],
      [true, "Cible Système multi-utilisateur atteinte."],
    ],
    startx: ["xinit : démarrage de la session graphique...", "chargement de pierreadam.js ▸"],
    welcome: "bienvenue. tapez 'help' pour afficher la liste des commandes.",
    helpTitle: "commandes disponibles :",
    cmds: {
      help: "afficher cette liste",
      whoami: "qui je suis",
      ls: "lister les fichiers",
      cat: "lire un fichier (ex. cat about.txt)",
      neofetch: "informations système, en plus joli",
      pay: "tester le terminal de paiement (pay 12,50, pay --offline)",
      matrix: "suivre le lapin blanc",
      hack: "pirater le mainframe",
      pwd: "où suis-je",
      date: "la date du jour",
      uname: "nom du système (essayez uname -a)",
      echo: "répéter ce que vous tapez",
      history: "commandes déjà tapées",
      man: "manuel d'une commande (ex. man pay)",
      lang: "changer de langue",
      restart: "revoir le site comme la première fois",
      clear: "effacer l'écran",
      exit: "fermer le terminal",
    },
    notFound: (c) => `commande introuvable : ${c}. essayez 'help'`,
    langSet: "langue : français",
    langUsage: (cur, list) => `usage : lang <${list.join("|")}>\nlangue actuelle : ${cur}`,
    langUnknown: (l) => `lang : langue inconnue '${l}'`,
    catMissing: "cat : nom de fichier manquant. essayez 'ls'",
    catNoFile: (f) => `cat : ${f} : aucun fichier ou dossier de ce nom`,
    manUsage: "quelle page de manuel voulez-vous ? ex. man cat",
    manNone: (c) => `aucune entrée de manuel pour ${c}`,
    uptime: (y) => `${y} ans dans le logiciel`,
    rm: "rm : bien essayé. ce CV est en lecture seule, tout comme ma base de production.",
    vim: "vous voilà coincé dans vim pour toujours. je plaisante, il n'y a pas d'éditeur ici.",
    cd: "cd : il n'y a que ~ ici. c'est un petit logement.",
    matrixEnd: "réveille-toi, guest... le CV te tient.",
    restart: ["Message de guest@pierreadam :", "Le système redémarre MAINTENANT !", "[  OK  ] Arrêt de pierreadam.js", "redémarrage..."],
    hack: {
      steps: ["contournement du pare-feu", "déchiffrement du mainframe", "téléchargement de cv.txt"],
      granted: "ACCÈS AUTORISÉ",
      end: "...il était public de toute façon. essayez 'cat about.txt'",
    },
    pay: {
      amount: "montant :",
      insert: "insérez ou présentez votre carte",
      reading: "lecture de la carte",
      pin: "code :",
      auth: "autorisation bancaire",
      offline: "perte du réseau !",
      offlineOk: "aucun souci : le cœur NF525 signe le ticket localement et le restaurant continue d'encaisser.",
      offlineTag: "HORS LIGNE, SYNCHRO EN ATTENTE",
      synced: "ticket mis en file d'attente, il sera transmis dès le retour du réseau.",
      approved: "ACCEPTÉ",
      shop: "CHEZ PIERRE",
      item: "café",
      thanks: "merci et à bientôt",
      invalid: "pay : montant invalide. usage : pay [montant] [--offline]",
    },
    sudo: "bien essayé. cet incident sera signalé.",
  },
};
